export default [
  {id: 1, name: 'American Light Lager', code: '1A'},
  {id: 2, name: 'American Lager', code: '1B'},
  {id: 3, name: 'Cream Ale', code: '1C'},
  {id: 4, name: 'American Wheat Beer', code: '1D'},
  {id: 5, name: 'International Pale Lager', code: '2A'},
  {id: 6, name: 'International Amber Lager', code: '2B'},
  {id: 7, name: 'International Dark Lager', code: '2C'},
  {id: 8, name: 'Czech Pale Lager', code: '3A'},
  {id: 9, name: 'Czech Premium Pale Lager', code: '3B'},
  {id: 10, name: 'Czech Amber Lager', code: '3C'},
  {id: 11, name: 'Czech Dark Lager', code: '3D'},
  {id: 12, name: 'Munich Helles', code: '4A'},
  {id: 13, name: 'Festbier', code: '4B'},
  {id: 14, name: 'Helles Bock', code: '4C'},
  {id: 15, name: 'German Leichtbier', code: '5A'},
  {id: 16, name: 'Kölsch', code: '5B'},
  {id: 17, name: 'German Helles Exportbier', code: '5C'},
  {id: 18, name: 'German Pils', code: '5D'},
  {id: 19, name: 'Märzen', code: '6A'},
  {id: 20, name: 'Rauchbier', code: '6B'},
  {id: 21, name: 'Dunkles Bock', code: '6C'},
  {id: 22, name: 'Vienna Lager', code: '7A'},
  {id: 23, name: 'Altbier', code: '7B'},
  {id: 24, name: 'Kellerbier', code: '7C'},
  {id: 25, name: 'Kellerbier: Pale Kellerbier', code: '7C'},
  {id: 26, name: 'Kellerbier: Amber Kellerbier', code: '7C'},
  {id: 27, name: 'Munich Dunkel', code: '8A'},
  {id: 28, name: 'Schwarzbier', code: '8B'},
  {id: 29, name: 'Doppelbock', code: '9A'},
  {id: 30, name: 'Eisbock', code: '9B'},
  {id: 31, name: 'Baltic Porter', code: '9C'},
  {id: 32, name: 'Weissbier', code: '10A'},
  {id: 33, name: 'Dunkles Weissbier', code: '10B'},
  {id: 34, name: 'Weizenbock', code: '10C'},
  {id: 35, name: 'Ordinary Bitter', code: '11A'},
  {id: 36, name: 'Best Bitter', code: '11B'},
  {id: 37, name: 'Strong Bitter', code: '11C'},
  {id: 38, name: 'British Golden Ale', code: '12A'},
  {id: 39, name: 'Australian Sparkling Ale', code: '12B'},
  {id: 40, name: 'English IPA', code: '12C'},
  {id: 41, name: 'Dark Mild', code: '13A'},
  {id: 42, name: 'British Brown Ale', code: '13B'},
  {id: 43, name: 'English Porter', code: '13C'},
  {id: 44, name: 'Scottish Light', code: '14A'},
  {id: 45, name: 'Scottish Heavy', code: '14B'},
  {id: 46, name: 'Scottish Export', code: '14C'},
  {id: 47, name: 'Irish Red Ale', code: '15A'},
  {id: 48, name: 'Irish Stout', code: '15B'},
  {id: 49, name: 'Irish Extra Stout', code: '15C'},
  {id: 50, name: 'Sweet Stout', code: '16A'},
  {id: 51, name: 'Oatmeal Stout', code: '16B'},
  {id: 52, name: 'Tropical Stout', code: '16C'},
  {id: 53, name: 'Foreign Extra Stout', code: '16D'},
  {id: 54, name: 'British Strong Ale', code: '17A'},
  {id: 55, name: 'Old Ale', code: '17B'},
  {id: 56, name: 'Wee Heavy', code: '17C'},
  {id: 57, name: 'English Barleywine', code: '17D'},
  {id: 58, name: 'Blonde Ale', code: '18A'},
  {id: 59, name: 'American Pale Ale', code: '18B'},
  {id: 60, name: 'American Amber Ale', code: '19A'},
  {id: 61, name: 'California Common', code: '19B'},
  {id: 62, name: 'American Brown Ale', code: '19C'},
  {id: 63, name: 'American Porter', code: '20A'},
  {id: 64, name: 'American Stout', code: '20B'},
  {id: 65, name: 'Imperial Stout', code: '20C'},
  {id: 66, name: 'American IPA', code: '21A'},
  {id: 67, name: 'Specialty IPA', code: '21B'},
  {id: 68, name: 'Belgian IPA', code: '21B'},
  {id: 69, name: 'Black IPA', code: '21B'},
  {id: 70, name: 'Brown IPA', code: '21B'},
  {id: 71, name: 'Red IPA', code: '21B'},
  {id: 72, name: 'Rye IPA', code: '21B'},
  {id: 73, name: 'White IPA', code: '21B'},
  {id: 74, name: 'Double IPA', code: '22A'},
  {id: 75, name: 'American Strong Ale', code: '22B'},
  {id: 76, name: 'American Barleywine', code: '22C'},
  {id: 77, name: 'Wheatwine', code: '22D'},
  {id: 78, name: 'Berliner Weisse', code: '23A'},
  {id: 79, name: 'Flanders Red Ale', code: '23B'},
  {id: 80, name: 'Oud Bruin', code: '23C'},
  {id: 81, name: 'Lambic', code: '23D'},
  {id: 82, name: 'Gueuze', code: '23E'},
  {id: 83, name: 'Fruit Lambic', code: '23F'},
  {id: 84, name: 'Witbier', code: '24A'},
  {id: 85, name: 'Belgian Pale Ale', code: '24B'},
  {id: 86, name: 'Bière de Garde', code: '24C'},
  {id: 87, name: 'Belgian Blond Ale', code: '25A'},
  {id: 88, name: 'Saison', code: '25B'},
  {id: 89, name: 'Belgian Golden Strong Ale', code: '25C'},
  {id: 90, name: 'Trappist Single', code: '26A'},
  {id: 91, name: 'Belgian Dubbel', code: '26B'},
  {id: 92, name: 'Belgian Tripel', code: '26C'},
  {id: 93, name: 'Belgian Dark Strong Ale', code: '26D'},
  {id: 94, name: 'Gose', code: '27'},
  {id: 95, name: 'Kentucky Common', code: '27'},
  {id: 96, name: 'Lichtenhainer', code: '27'},
  {id: 97, name: 'London Brown Ale', code: '27'},
  {id: 98, name: 'Piwo Grodziskie', code: '27'},
  {id: 99, name: 'Pre-Prohibition Lager', code: '27'},
  {id: 100, name: 'Pre-Prohibition Porter', code: '27'},
  {id: 101, name: 'Roggenbier', code: '27'},
  {id: 102, name: 'Sahti', code: '27'},
  {id: 103, name: 'Brett Beer', code: '28A'},
  {id: 104, name: 'Mixed-Fermentation Sour Beer', code: '28B'},
  {id: 105, name: 'Wild Specialty Beer', code: '28C'},
  {id: 106, name: 'Fruit Beer', code: '29A'},
  {id: 107, name: 'Fruit and Spice Beer', code: '29B'},
  {id: 108, name: 'Specialty Fruit Beer', code: '29C'},
  {id: 109, name: 'Spice, Herb, or Vegetable Beer', code: '30A'},
  {id: 110, name: 'Autumn Seasonal Beer', code: '30B'},
  {id: 111, name: 'Winter Seasonal Beer', code: '30C'},
  {id: 112, name: 'Alternative Grain Beer', code: '31A'},
  {id: 113, name: 'Alternative Sugar Beer', code: '31B'},
  {id: 114, name: 'Classic Style Smoked Beer', code: '32A'},
  {id: 115, name: 'Specialty Smoked Beer', code: '32B'},
  {id: 116, name: 'Wood-Aged Beer', code: '33A'},
  {id: 117, name: 'Specialty Wood-Aged Beer', code: '33B'},
  {id: 118, name: 'Clone Beer', code: '34A'},
  {id: 119, name: 'Mixed-Style Beer', code: '34B'},
  {id: 120, name: 'Experimental Beer', code: '34C'}
];