 export default [
   {name:"American Light Lager",code:"1A"},
   {name:"American Lager",code:"1B"},
   {name:"Cream Ale",code:"1C"},
   {name:"American Wheat Beer",code:"1D"},
   {name:"International Pale Lager",code:"2A"},
   {name:"International Amber Lager",code:"2B"},
   {name:"International Dark Lager",code:"2C"},
   {name:"Czech Pale Lager",code:"3A"},
   {name:"Czech Premium Pale Lager",code:"3B"},
   {name:"Czech Amber Lager",code:"3C"},
   {name:"Czech Dark Lager",code:"3D"},
   {name:"Munich Helles",code:"4A"},
   {name:"Festbier",code:"4B"},
   {name:"Helles Bock",code:"4C"},
   {name:"German Leichtbier",code:"5A"},
   {name:"Kölsch",code:"5B"},
   {name:"German Helles Exportbier",code:"5C"},
   {name:"German Pils",code:"5D"},
   {name:"Märzen",code:"6A"},
   {name:"Rauchbier",code:"6B"},
   {name:"Dunkles Bock",code:"6C"},
   {name:"Vienna Lager",code:"7A"},
   {name:"Altbier",code:"7B"},
   {name:"Kellerbier",code:"7C"},
   {name:"Munich Dunkel",code:"8A"},
   {name:"Schwarzbier",code:"8B"},
   {name:"Doppelbock",code:"9A"},
   {name:"Eisbock",code:"9B"},
   {name:"Baltic Porter",code:"9C"},
   {name:"Weissbier",code:"10A"},
   {name:"Dunkles Weissbier",code:"10B"},
   {name:"Weizenbock",code:"10C"},
   {name:"Ordinary Bitter",code:"11A"},
   {name:"Best Bitter",code:"11B"},
   {name:"Strong Bitter",code:"11C"},
   {name:"British Golden Ale",code:"12A"},
   {name:"Australian Sparkling Ale",code:"12B"},
   {name:"English IPA",code:"12C"},
   {name:"Dark Mild",code:"13A"},
   {name:"British Brown Ale",code:"13B"},
   {name:"English Porter",code:"13C"},
   {name:"Scottish Light",code:"14A"},
   {name:"Scottish Heavy",code:"14B"},
   {name:"Scottish Export",code:"14C"},
   {name:"Irish Red Ale",code:"15A"},
   {name:"Irish Stout",code:"15B"},
   {name:"Irish Extra Stout",code:"15C"},
   {name:"Sweet Stout",code:"16A"},
   {name:"Oatmeal Stout",code:"16B"},
   {name:"Tropical Stout",code:"16C"},
   {name:"Foreign Extra Stout",code:"16D"},
   {name:"British Strong Ale",code:"17A"},
   {name:"Old Ale",code:"17B"},
   {name:"Wee Heavy",code:"17C"},
   {name:"English Barleywine",code:"17D"},
   {name:"Blonde Ale",code:"18A"},
   {name:"American Pale Ale",code:"18B"},
   {name:"American Amber Ale",code:"19A"},
   {name:"California Common",code:"19B"},
   {name:"American Brown Ale",code:"19C"},
   {name:"American Porter",code:"20A"},
   {name:"American Stout",code:"20B"},
   {name:"Imperial Stout",code:"20C"},
   {name:"American IPA",code:"21A"},
   {name:"Specialty IPA",code:"21B"},
   {name:"Belgian IPA",code:""},
   {name:"Black IPA",code:""},
   {name:"Brown IPA",code:""},
   {name:"Red IPA",code:""},
   {name:"Rye IPA",code:""},
   {name:"White IPA",code:""},
   {name:"Double IPA",code:"22A"},
   {name:"American Strong Ale",code:"22B"},
   {name:"American Barleywine",code:"22C"},
   {name:"Wheatwine",code:"22D"},
   {name:"Berliner Weisse",code:"23A"},
   {name:"Flanders Red Ale",code:"23B"},
   {name:"Oud Bruin",code:"23C"},
   {name:"Lambic",code:"23D"},
   {name:"Gueuze",code:"23E"},
   {name:"Fruit Lambic",code:"23F"},
   {name:"Witbier",code:"24A"},
   {name:"Belgian Pale Ale",code:"24B"},
   {name:"Bière de Garde",code:"24C"},
   {name:"Belgian Blond Ale",code:"25A"},
   {name:"Saison",code:"25B"},
   {name:"Belgian Golden Strong Ale",code:"25C"},
   {name:"Trappist Single",code:"26A"},
   {name:"Belgian Dubbel",code:"26B"},
   {name:"Belgian Tripel",code:"26C"},
   {name:"Belgian Dark Strong Ale",code:"26D"},
   {name:"Gose",code:""},
   {name:"Kentucky Common",code:""},
   {name:"Lichtenhainer",code:""},
   {name:"Piwo Grodziskie",code:""},
   {name:"Pre-Prohibition Lager",code:""},
   {name:"Pre-Prohibition Porter",code:""},
   {name:"Roggenbier",code:""},
   {name:"Sahti",code:""},
   {name:"Brett Beer",code:"28A"},
   {name:"Mixed-Fermentation Sour Beer",code:"28B"},
   {name:"Wild Specialty Beer",code:"28C"},
   {name:"Fruit Beer",code:"29A"},
   {name:"Fruit and Spice Beer",code:"29B"},
   {name:"Specialty Fruit Beer",code:"29C"},
   {name:"Spice, Herb, or Vegetable Beer",code:"30A"},
   {name:"Autumn Seasonal Beer",code:"30B"},
   {name:"Winter Seasonal Beer",code:"30C"},
   {name:"Alternative Grain Beer",code:"31A"},
   {name:"Alternative Sugar Beer",code:"31B"},
   {name:"Classic Style Smoked Beer",code:"32A"},
   {name:"Specialty Smoked Beer",code:"32B"},
   {name:"Wood-Aged Beer",code:"33A"},
   {name:"Specialty Wood-Aged Beer",code:"33B"},
   {name:"Clone Beer",code:"34A"},
   {name:"Mixed-Style Beer",code:"34B"},
   {name:"Experimental Beer",code:"34C"}
 ];