import keyMirror from 'fbjs/lib/keyMirror';

export default keyMirror({
  /* grain */
  AddGrain: null,
  RemoveGrain: null,
  SetGrainWeight: null,
  SetGrainGravity: null,
  SetGrainLovibond: null,
  SetGrainLintner: null,
  SetGrainExtractType: null,
  /* hops */
  AddHop: null,
  RemoveHop: null,
  SetHopForm: null,
  SetHopAlpha: null,
  SetHopBeta: null,
  AddHopAddition: null,
  SetHopAdditionType: null,
  SetHopAdditionTime: null,
  SetHopAdditionWeight: null,
  RemoveHopAddition: null,
  /* mash */
  SetMashStyle: null,
  SetMashThickness: null,
  SetBoilOff: null,
  SetGrainAbsorption: null,
  SetInfusionTemp: null,
  SetMashoutTemp: null,
  SetGrainTemp: null,
  SetBoilVolume: null,
  SetTargetVolume: null,
  SetBoilTime: null,
  SetEfficiency: null,
  AddRest: null,
  RemoveRest: null,
  SetRestTemperature: null,
  /* recipe */
  LoadSavedRecipe: null,
  SaveRecipe: null,
  RecipeSaved: null,
  SetRecipeName: null,
  SetRecipeStyle: null,
  SetRecipeMethod: null,
  ClearRecipe: null,
  UpdateRecipeText: null,
  ParseRecipeText: null,
  /* yeast */
  SetPitchRate: null,
  AddYeast: null,
  RemoveYeast: null,
  AddStarterStep: null,
  RemoveStarterStep: null,
  SetYeastMfgDate: null,
  SetYeastAttenuation: null,
  SetYeastViability: null,
  SetYeastQuantity: null
});