import keyMirror from 'fbjs/lib/keyMirror';

export default keyMirror({
  AddGrain: null,
  RemoveGrain: null,
  SetGrainWeight: null,
  SetGrainGravity: null,
  SetGrainLovibond: null,
  AddHop: null,
  RemoveHop: null,
  SetHopAlpha: null,
  SetHopBeta: null,
  AddHopAddition: null,
  SetHopAdditionTime: null,
  SetHopAdditionWeight: null,
  RemoveHopAddition: null,
  SetMashStyle: null,
  SetMashThickness: null,
  SetBoilOff: null,
  SetGrainAbsorption: null,
  SetInfusionTemp: null,
  SetMashoutTemp: null,
  SetGrainTemp: null,
  LoadSavedRecipe: null,
  SaveRecipe: null,
  RecipeSaved: null,
  SetRecipeName: null,
  SetRecipeStyle: null,
  SetBoilVolume: null,
  SetTargetVolume: null,
  SetBoilTime: null,
  SetEfficiency: null,
  SetPitchRate: null,
  AddYeast: null,
  RemoveYeast: null,
  AddStarterStep: null,
  RemoveStarterStep: null,
  SetYeastMfgDate: null,
  SetYeastAttenuation: null,
  SetYeastViability: null,
  SetYeastQuantity: null
});