const YeastLookup = [
  { id: 1, name: 'California Ale Yeast', mfg: 'White Labs', attenuation: '73%-80%', temp: '68 °F-73 °F', tolerance: '15%' },
  { id: 2, name: 'English Ale Yeast', mfg: 'White Labs', attenuation: '63%-70%', temp: '65 °F-68 °F', tolerance: '10%' },
  { id: 3, name: 'Irish Ale Yeast', mfg: 'White Labs', attenuation: '69%-74%', temp: '65 °F-68 °F', tolerance: '12%' },
  { id: 4, name: 'British Ale Yeast', mfg: 'White Labs', attenuation: '67%-74%', temp: '65 °F-70 °F', tolerance: '10%' },
  { id: 5, name: 'Bedford British', mfg: 'White Labs', attenuation: '72%-80%', temp: '65 °F-70 °F', tolerance: '10%' },
  { id: 6, name: 'Dry English Ale Yeast', mfg: 'White Labs', attenuation: '70%-80%', temp: '65 °F-70 °F', tolerance: '12%' },
  { id: 7, name: 'East Coast Ale Yeast', mfg: 'White Labs', attenuation: '70%-75%', temp: '68 °F-73 °F', tolerance: '10%' },
  { id: 8, name: 'Australian Ale Yeast', mfg: 'White Labs', attenuation: '70%-75%', temp: '65 °F-70 °F', tolerance: '10%' },
  { id: 9, name: 'European Ale Yeast', mfg: 'White Labs', attenuation: '65%-70%', temp: '65 °F-70 °F', tolerance: '10%' },
  { id: 10, name: 'London Ale Yeast', mfg: 'White Labs', attenuation: '67%-75%', temp: '66 °F-71 °F', tolerance: '10%' },
  { id: 11, name: 'Whitbread Ale Yeast', mfg: 'White Labs', attenuation: '67%-73%', temp: '66 °F-70 °F', tolerance: '10%' },
  { id: 12, name: 'Essex Ale Yeast', mfg: 'White Labs', attenuation: '71%-76%', temp: '66 °F-70 °F', tolerance: '10%' },
  { id: 13, name: 'Burton Ale Yeast', mfg: 'White Labs', attenuation: '69%-75%', temp: '68 °F-73 °F', tolerance: '10%' },
  { id: 14, name: 'Edinburgh Scottish Ale Yeast', mfg: 'White Labs', attenuation: '70%-75%', temp: '65 °F-70 °F', tolerance: '12%' },
  { id: 15, name: 'German Ale/ Kolsch Yeast', mfg: 'White Labs', attenuation: '72%-78%', temp: '65 °F-69 °F', tolerance: '10%' },
  { id: 16, name: 'Dusseldorf Alt Yeast', mfg: 'White Labs', attenuation: '65%-72%', temp: '65 °F-69 °F', tolerance: '10%' },
  { id: 17, name: 'Yorkshire Square Ale Yeast', mfg: 'White Labs', attenuation: '68%-72%', temp: '65 °F-70 °F', tolerance: '12%' },
  { id: 18, name: 'Manchester Ale Yeast', mfg: 'White Labs', attenuation: '70%-74%', temp: '65 °F-70 °F', tolerance: '12%' },
  { id: 19, name: 'East Midlands Ale Yeast', mfg: 'White Labs', attenuation: '73%-82%', temp: '66 °F-70 °F', tolerance: '10%' },
  { id: 20, name: 'Pacific Ale Yeast', mfg: 'White Labs', attenuation: '65%-70%', temp: '65 °F-68 °F', tolerance: '10%' },
  { id: 21, name: 'Scotch Whisky Yeast', mfg: 'White Labs', attenuation: '75%-80%', temp: '72 °F-77 °F', tolerance: '15%' },
  { id: 22, name: 'Tennessee Whiskey Yeast', mfg: 'White Labs', attenuation: '75%-80%', temp: '75 °F-79 °F', tolerance: '15%' },
  { id: 23, name: 'California Ale V Yeast', mfg: 'White Labs', attenuation: '70%-75%', temp: '66 °F-70 °F', tolerance: '12%' },
  { id: 24, name: 'American Ale Yeast Blend', mfg: 'White Labs', attenuation: '72%-80%', temp: '68 °F-72 °F', tolerance: '12%' },
  { id: 25, name: 'American Whiskey Yeast', mfg: 'White Labs', attenuation: '76%-82%', temp: '75 °F-82 °F', tolerance: '15%' },
  { id: 26, name: 'Bourbon Yeast', mfg: 'White Labs', attenuation: '75%-80%', temp: '72 °F-77 °F', tolerance: '15%' },
  { id: 27, name: 'French Ale', mfg: 'White Labs', attenuation: '68%-75%', temp: '63 °F-73 °F', tolerance: '10%' },
  { id: 28, name: 'Old Sonoma Ale Yeast', mfg: 'White Labs', attenuation: '70%-74%', temp: '66 °F-70 °F', tolerance: '10%' },
  { id: 29, name: 'Neutral Grain Yeast', mfg: 'White Labs', attenuation: '77%-84%', temp: '76 °F-85 °F', tolerance: '15%' },
  { id: 30, name: 'Cream Ale Yeast Blend', mfg: 'White Labs', attenuation: '75%-80%', temp: '65 °F-70 °F', tolerance: '12%' },
  { id: 31, name: 'English Ale Blend', mfg: 'White Labs', attenuation: '69%-76%', temp: '68 °F-72 °F', tolerance: 'N/A' },
  { id: 32, name: 'San Diego Super Yeast', mfg: 'White Labs', attenuation: '76%-83%', temp: '65 °F-68 °F', tolerance: '15%' },
  { id: 33, name: 'Super High Gravity Ale Yeast', mfg: 'White Labs', attenuation: '80%-100%', temp: '65 °F-69 °F', tolerance: '25%' },
  { id: 34, name: 'Hefeweizen Ale Yeast', mfg: 'White Labs', attenuation: '72%-76%', temp: '68 °F-72 °F', tolerance: '10%' },
  { id: 35, name: 'American Hefeweizen Ale Yeast', mfg: 'White Labs', attenuation: '70%-75%', temp: '65 °F-69 °F', tolerance: '10%' },
  { id: 36, name: 'Bavarian Weizen Yeast', mfg: 'White Labs', attenuation: '73%-77%', temp: '66 °F-70 °F', tolerance: '10%' },
  { id: 37, name: 'Hefeweizen IV Ale Yeast', mfg: 'White Labs', attenuation: '73%-80%', temp: '66 °F-70 °F', tolerance: '10%' },
  { id: 38, name: 'Belgian Wit Ale Yeast', mfg: 'White Labs', attenuation: '74%-78%', temp: '67 °F-74 °F', tolerance: '10%' },
  { id: 39, name: 'Belgian Wit II Ale Yeast', mfg: 'White Labs', attenuation: '70%-75%', temp: '67 °F-74 °F', tolerance: '10%' },
  { id: 40, name: 'Trappist Ale Yeast', mfg: 'White Labs', attenuation: '75%-80%', temp: '65 °F-72 °F', tolerance: '15%' },
  { id: 41, name: 'Bastogne Belgian Ale Yeast', mfg: 'White Labs', attenuation: '74%-80%', temp: '66 °F-72 °F', tolerance: '15%' },
  { id: 42, name: 'Antwerp Ale Yeast', mfg: 'White Labs', attenuation: '73%-80%', temp: '67 °F-70 °F', tolerance: '10%' },
  { id: 43, name: 'Abbey Ale Yeast', mfg: 'White Labs', attenuation: '75%-80%', temp: '66 °F-72 °F', tolerance: '15%' },
  { id: 44, name: 'Abbey IV Ale Yeast', mfg: 'White Labs', attenuation: '74%-82%', temp: '66 °F-72 °F', tolerance: '15%' },
  { id: 45, name: 'Belgian Strong Ale Yeast', mfg: 'White Labs', attenuation: '78%-85%', temp: '66 °F-72 °F', tolerance: '15%' },
  { id: 46, name: 'Belgian Ale Yeast', mfg: 'White Labs', attenuation: '78%-85%', temp: '68 °F-78 °F', tolerance: '12%' },
  { id: 47, name: 'Belgian Saison I Yeast', mfg: 'White Labs', attenuation: '65%-75%', temp: '68 °F-75 °F', tolerance: '10%' },
  { id: 48, name: 'Belgian Saison II Yeast', mfg: 'White Labs', attenuation: '78%-85%', temp: '68 °F-78 °F', tolerance: '10%' },
  { id: 49, name: 'Belgian Style Saison Ale Yeast Blend', mfg: 'White Labs', attenuation: '70%-80%', temp: '70 °F-80 °F', tolerance: '10%' },
  { id: 50, name: 'Belgian Golden Ale Yeast', mfg: 'White Labs', attenuation: '73%-78%', temp: '68 °F-75 °F', tolerance: '15%' },
  { id: 51, name: 'Belgian Style Ale Yeast Blend', mfg: 'White Labs', attenuation: '74%-80%', temp: '68 °F-75 °F', tolerance: '12%' },
  { id: 52, name: 'Belgian Saison III Yeast', mfg: 'White Labs', attenuation: '70%-74%', temp: '68 °F-75 °F', tolerance: '10%' },
  { id: 53, name: 'Berliner Weisse Blend', mfg: 'White Labs', attenuation: '73%-80%', temp: '68 °F-72 °F', tolerance: '10%' },
  { id: 54, name: 'Brettanomyces bruxellensis Trois', mfg: 'White Labs', attenuation: '85%-100%', temp: '70 °F-85 °F', tolerance: '12%' },
  { id: 55, name: 'Brettanomyces claussenii', mfg: 'White Labs', attenuation: '70%-85%', temp: '85 °F+', tolerance: '12%' },
  { id: 56, name: 'Brettanomyces bruxellensis', mfg: 'White Labs', attenuation: '70%-85%', temp: '85 °F+', tolerance: '12%' },
  { id: 57, name: 'Brettanomyces lambicus', mfg: 'White Labs', attenuation: '70%-85%', temp: '85 °F+', tolerance: '12%' },
  { id: 58, name: 'Belgian Sour Mix 1', mfg: 'White Labs', attenuation: '70%-80%', temp: '80 °F-85 °F', tolerance: '12%' },
  { id: 59, name: 'Flemish Ale Blend', mfg: 'White Labs', attenuation: '80%-85%', temp: '68 °F-80 °F', tolerance: '12%' },
  { id: 60, name: 'American Farmhouse Blend', mfg: 'White Labs', attenuation: '75%-82%', temp: '68 °F-72 °F', tolerance: '10%' },
  { id: 61, name: 'Malolactic Cultures', mfg: 'White Labs', attenuation: 'Any', temp: 'Any', tolerance: 'N/A' },
  { id: 62, name: 'Lactobacillus Bacteria', mfg: 'White Labs', attenuation: '75%-82%', temp: '70 °F-75 °F', tolerance: '12%' },
  { id: 63, name: 'Flor Sherrry Yeast', mfg: 'White Labs', attenuation: '80%-100%', temp: '70 °F+', tolerance: '16%' },
  { id: 64, name: 'Sake Yeast', mfg: 'White Labs', attenuation: '80%-100%', temp: '70 °F+', tolerance: '16%' },
  { id: 65, name: 'California Pinot Noir Yeast', mfg: 'White Labs', attenuation: '80%-100%', temp: '70 °F+', tolerance: '16%' },
  { id: 66, name: 'Sake #9 Yeast', mfg: 'White Labs', attenuation: '72%-78%', temp: '62 °F-68 °F', tolerance: '16%' },
  { id: 67, name: 'Champagne Yeast', mfg: 'White Labs', attenuation: '75%-100%', temp: '70 °F-75 °F', tolerance: '17%' },
  { id: 68, name: 'Avize Wine Yeast', mfg: 'White Labs', attenuation: '80%-100%', temp: '60 °F-90 °F', tolerance: '15%' },
  { id: 69, name: 'Sweet Mead/Wine Yeast', mfg: 'White Labs', attenuation: '0%-75%', temp: '70 °F-75 °F', tolerance: '15%' },
  { id: 70, name: 'Steinberg-Geisenheim Wine Yeast', mfg: 'White Labs', attenuation: '80%-100%', temp: '50 °F-90 °F', tolerance: '14%' },
  { id: 71, name: 'Chardonnay White Wine Yeast', mfg: 'White Labs', attenuation: '80%-100%', temp: '50 °F-90 °F', tolerance: '14%' },
  { id: 72, name: 'French White Wine Yeast', mfg: 'White Labs', attenuation: '80%-100%', temp: '60 °F-90 °F', tolerance: '16%' },
  { id: 73, name: 'Merlot Red Wine Yeast', mfg: 'White Labs', attenuation: '80%-100%', temp: '60 °F-90 °F', tolerance: '18%' },
  { id: 74, name: 'Assmanshausen Wine Yeast', mfg: 'White Labs', attenuation: '80%-100%', temp: '50 °F-90 °F', tolerance: '16%' },
  { id: 75, name: 'French Red Wine Yeast', mfg: 'White Labs', attenuation: '80%-100%', temp: '60 °F-90 °F', tolerance: '17%' },
  { id: 76, name: 'Cabernet Red Wine Yeast', mfg: 'White Labs', attenuation: '80%-100%', temp: '60 °F-90 °F', tolerance: '16%' },
  { id: 77, name: 'Suremain Burgundy Wine Yeast', mfg: 'White Labs', attenuation: '80%-100%', temp: '60 °F-90 °F', tolerance: '16%' },
  { id: 78, name: 'English Cider Yeast', mfg: 'White Labs', attenuation: '80%-100%', temp: '68 °F-75 °F', tolerance: '12%' },
  { id: 79, name: 'Pilsner Lager Yeast', mfg: 'White Labs', attenuation: '72%-77%', temp: '50 °F-55 °F', tolerance: '10%' },
  { id: 80, name: 'Czech Budejovice Lager Yeast', mfg: 'White Labs', attenuation: '75%-80%', temp: '50 °F-55 °F', tolerance: '10%' },
  { id: 81, name: 'San Francisco Lager Yeast', mfg: 'White Labs', attenuation: '65%-70%', temp: '58 °F-65 °F', tolerance: '12%' },
  { id: 82, name: 'Belgian Lager Yeast', mfg: 'White Labs', attenuation: '72%-78%', temp: '50 °F-55 °F', tolerance: '10%' },
  { id: 83, name: 'Oktoberfest/Märzen Lager Yeast', mfg: 'White Labs', attenuation: '65%-73%', temp: '52 °F-58 °F', tolerance: '12%' },
  { id: 84, name: 'German Lager Yeast', mfg: 'White Labs', attenuation: '74%-79%', temp: '50 °F-55 °F', tolerance: '10%' },
  { id: 85, name: 'German Bock Lager Yeast', mfg: 'White Labs', attenuation: '70%-76%', temp: '48 °F-55 °F', tolerance: '12%' },
  { id: 86, name: 'Southern German Lager Yeast', mfg: 'White Labs', attenuation: '68%-76%', temp: '50 °F-55 °F', tolerance: '10%' },
  { id: 87, name: 'American Lager Yeast', mfg: 'White Labs', attenuation: '75%-80%', temp: '50 °F-55 °F', tolerance: '10%' },
  { id: 88, name: 'Munich Helles Yeast', mfg: 'White Labs', attenuation: '68%-72%', temp: '48 °F-52 °F', tolerance: '10%' },
  { id: 89, name: 'Cry Havoc', mfg: 'White Labs', attenuation: '66%-70%', temp: '55 °F-58 °F', tolerance: 'N/A' },
  { id: 90, name: 'Zurich Lager Yeast', mfg: 'White Labs', attenuation: '70%-80%', temp: '50 °F-55 °F', tolerance: 'N/A' },
  { id: 91, name: 'Old Bavarian Lager Yeast', mfg: 'White Labs', attenuation: '66%-73%', temp: '50 °F-55 °F', tolerance: '12%' },
  { id: 92, name: 'Mexican Lager Yeast', mfg: 'White Labs', attenuation: '70%-78%', temp: '50 °F-55 °F', tolerance: '10%' },
  { id: 93, name: 'Budvar Lager', mfg: 'Wyeast', attenuation: '71%-75%', temp: '48 °F-56 °F', tolerance: '9%' },
  { id: 94, name: 'Urquell Lager', mfg: 'Wyeast', attenuation: '72%-76%', temp: '48 °F-56 °F', tolerance: '9%' },
  { id: 95, name: 'Pilsen Lager', mfg: 'Wyeast', attenuation: '71%-75%', temp: '48 °F-56 °F', tolerance: '9%' },
  { id: 96, name: 'American Lager', mfg: 'Wyeast', attenuation: '73%-77%', temp: '48 °F-58 °F', tolerance: '9%' },
  { id: 97, name: 'Danish lager', mfg: 'Wyeast', attenuation: '73%-77%', temp: '46 °F-56 °F', tolerance: '9%' },
  { id: 98, name: 'California Lager', mfg: 'Wyeast', attenuation: '67%-71%', temp: '58 °F-68 °F', tolerance: '9%' },
  { id: 99, name: 'Bohemian Lager', mfg: 'Wyeast', attenuation: '73%-77%', temp: '45 °F-68 °F', tolerance: '9%' },
  { id: 100, name: 'Bavarian Lager', mfg: 'Wyeast', attenuation: '73%-77%', temp: '46 °F-58 °F', tolerance: '9%' },
  { id: 101, name: 'Czech Pils', mfg: 'Wyeast', attenuation: '70%-74%', temp: '50 °F-58 °F', tolerance: '9%' },
  { id: 102, name: 'Munich Lager', mfg: 'Wyeast', attenuation: '70%-74%', temp: '48 °F-56 °F', tolerance: '9%' },
  { id: 103, name: 'Octoberfest Lager Blend', mfg: 'Wyeast', attenuation: '73%-77%', temp: '48 °F-58 °F', tolerance: '9%' },
  { id: 104, name: 'German Ale', mfg: 'Wyeast', attenuation: '73%-77%', temp: '55 °F-68 °F', tolerance: '11%' },
  { id: 105, name: 'American Wheat', mfg: 'Wyeast', attenuation: '74%-78%', temp: '58 °F-74 °F', tolerance: '10%' },
  { id: 106, name: 'London Ale', mfg: 'Wyeast', attenuation: '73%-77%', temp: '60 °F-72 °F', tolerance: '11%' },
  { id: 107, name: 'American Ale', mfg: 'Wyeast', attenuation: '73%-77%', temp: '60 °F-72 °F', tolerance: '11%' },
  { id: 108, name: 'Irish Ale', mfg: 'Wyeast', attenuation: '71%-75%', temp: '62 °F-72 °F', tolerance: '12%' },
  { id: 109, name: 'British Ale', mfg: 'Wyeast', attenuation: '73%-75%', temp: '64 °F-72 °F', tolerance: '10%' },
  { id: 110, name: 'Whitbread Ale', mfg: 'Wyeast', attenuation: '68%-72%', temp: '64 °F-75 °F', tolerance: '10%' },
  { id: 111, name: 'Ringwood Ale', mfg: 'Wyeast', attenuation: '68%-72%', temp: '64 °F-74 °F', tolerance: '10%' },
  { id: 112, name: 'American Ale II', mfg: 'Wyeast', attenuation: '72%-76%', temp: '60 °F-72 °F', tolerance: '10%' },
  { id: 113, name: 'Thames Valley Ale', mfg: 'Wyeast', attenuation: '72%-76%', temp: '62 °F-72 °F', tolerance: '10%' },
  { id: 114, name: 'London Ale III', mfg: 'Wyeast', attenuation: '71%-75%', temp: '64 °F-74 °F', tolerance: '10%' },
  { id: 115, name: 'Northwest Ale', mfg: 'Wyeast', attenuation: '67%-71%', temp: '65 °F-75 °F', tolerance: '10%' },
  { id: 116, name: 'British Ale II', mfg: 'Wyeast', attenuation: '73%-76%', temp: '63 °F-75 °F', tolerance: '10%' },
  { id: 117, name: 'Denny\'s Favorite 50', mfg: 'Wyeast', attenuation: '74%-76%', temp: '60 °F-70 °F', tolerance: '10%' },
  { id: 118, name: 'West Yorkshire Ale', mfg: 'Wyeast', attenuation: '67%-71%', temp: '64 °F-72 °F', tolerance: '9%' },
  { id: 119, name: 'Scottish Ale', mfg: 'Wyeast', attenuation: '69%-73%', temp: '55 °F-75 °F', tolerance: '12%' },
  { id: 120, name: 'London ESB Ale', mfg: 'Wyeast', attenuation: '67%-71%', temp: '64 °F-72 °F', tolerance: '9%' },
  { id: 121, name: 'Kölsch', mfg: 'Wyeast', attenuation: '73%-77%', temp: '56 °F-70 °F', tolerance: '10%' },
  { id: 122, name: 'Belgian Abbey', mfg: 'Wyeast', attenuation: '74%-78%', temp: '68 °F-78 °F', tolerance: '12%' },
  { id: 123, name: 'Belgian Strong Ale', mfg: 'Wyeast', attenuation: '74%-78%', temp: '64 °F-80 °F', tolerance: '13%' },
  { id: 124, name: 'Belgian Abbey II', mfg: 'Wyeast', attenuation: '73%-77%', temp: '65 °F-75 °F', tolerance: '12%' },
  { id: 125, name: 'Bavarian Wheat Blend', mfg: 'Wyeast', attenuation: '73%-77%', temp: '64 °F-74 °F', tolerance: '10%' },
  { id: 126, name: 'Weihenstephan Weizen', mfg: 'Wyeast', attenuation: '73%-77%', temp: '64 °F-75 °F', tolerance: '10%' },
  { id: 127, name: 'German Wheat', mfg: 'Wyeast', attenuation: '70%-76%', temp: '63 °F-75 °F', tolerance: '10%' },
  { id: 128, name: 'Forbidden Fruit', mfg: 'Wyeast', attenuation: '72%-76%', temp: '63 °F-76 °F', tolerance: '12%' },
  { id: 129, name: 'Belgian Ardennes', mfg: 'Wyeast', attenuation: '72%-76%', temp: '65 °F-76 °F', tolerance: '12%' },
  { id: 130, name: 'Bavarian Wheat', mfg: 'Wyeast', attenuation: '70%-76%', temp: '64 °F-75 °F', tolerance: '10%' },
  { id: 131, name: 'French Saison', mfg: 'Wyeast', attenuation: '77%-83%', temp: '65 °F-77 °F', tolerance: '12%' },
  { id: 132, name: 'Belgian Saison', mfg: 'Wyeast', attenuation: '76%-80%', temp: '70 °F-95 °F', tolerance: '12%' },
  { id: 133, name: 'Trappist High Gravity', mfg: 'Wyeast', attenuation: '74%-78%', temp: '64 °F-78 °F', tolerance: '12%' },
  { id: 134, name: 'Belgian Wheat', mfg: 'Wyeast', attenuation: '72%-76%', temp: '64 °F-74 °F', tolerance: '12%' },
  { id: 135, name: 'Belgian Wit', mfg: 'Wyeast', attenuation: '72%-76%', temp: '62 °F-75 °F', tolerance: '12%' },
  { id: 136, name: 'Safale S-04', mfg: 'Fermentis', attenuation: '75%+', temp: '54 °F-77 °F', tolerance: 'N/A' },
  { id: 137, name: 'Safale US-05', mfg: 'Fermentis', attenuation: '81%+', temp: '54 °F-77 °F', tolerance: 'N/A' },
  { id: 138, name: 'Safale K-97', mfg: 'Fermentis', attenuation: '81%+', temp: '54 °F-77 °F', tolerance: 'N/A' },
  { id: 139, name: 'Saflager S-23', mfg: 'Fermentis', attenuation: '82%+', temp: '48 °F-72 °F', tolerance: 'N/A' },
  { id: 140, name: 'Saflager W-34/70', mfg: 'Fermentis', attenuation: '83%+', temp: '48 °F-72 °F', tolerance: 'N/A' },
  { id: 141, name: 'Saflager S-189', mfg: 'Fermentis', attenuation: '84%+', temp: '48 °F-72 °F', tolerance: 'N/A' },
  { id: 142, name: 'Safbrew T-58', mfg: 'Fermentis', attenuation: '70%+', temp: '54 °F-77 °F', tolerance: 'N/A' },
  { id: 143, name: 'Safbrew S-33', mfg: 'Fermentis', attenuation: '70%+', temp: '54 °F-77 °F', tolerance: 'N/A' },
  { id: 144, name: 'Safbrew WB-06', mfg: 'Fermentis', attenuation: '86%+', temp: '54 °F-77 °F', tolerance: 'N/A' },
  { id: 145, name: 'Vermont Ale', mfg: 'The Yeast Bay', attenuation: '75%-82%', temp: '66 °F-70 °F', tolerance: 'N/A' },
  { id: 146, name: 'Wallonian Farmhouse', mfg: 'The Yeast Bay', attenuation: '81%-88%', temp: '68 °F-78 °F', tolerance: 'N/A' },
  { id: 147, name: 'Northeastern Abbey', mfg: 'The Yeast Bay', attenuation: '77%-81%', temp: '68 °F-73 °F', tolerance: 'N/A' },
  { id: 148, name: 'Saison Blend', mfg: 'The Yeast Bay', attenuation: '76%-82%', temp: '68 °F-80 °F', tolerance: 'N/A' },
  { id: 149, name: 'Dry Belgian Ale', mfg: 'The Yeast Bay', attenuation: '85%-100%', temp: '70 °F-76 °F', tolerance: 'N/A' },
  { id: 150, name: 'Scottish Heavy', mfg: 'East Coast Yeast', attenuation: '77%-80%', temp: '60 °F-68 °F', tolerance: 'N/A' },
  { id: 151, name: 'Saison Brasserie', mfg: 'East Coast Yeast', attenuation: '80%+', temp: '75 °F-85 °F', tolerance: 'N/A' },
  { id: 152, name: 'Belgian Abbaye', mfg: 'East Coast Yeast', attenuation: '74%-76%', temp: '66 °F-72 °F', tolerance: 'N/A' },
  { id: 153, name: 'Old Newark Ale', mfg: 'East Coast Yeast', attenuation: '76%+', temp: '60 °F-68 °F', tolerance: 'N/A' },
  { id: 154, name: 'Belgian White', mfg: 'East Coast Yeast', attenuation: '76%+', temp: '70 °F-76 °F', tolerance: 'N/A' },
  { id: 155, name: 'Old Newark Beer', mfg: 'East Coast Yeast', attenuation: '78%+', temp: '58 °F-68 °F', tolerance: 'N/A' },
  { id: 156, name: 'Belgian Abbaye 2', mfg: 'East Coast Yeast', attenuation: '74%-76%', temp: '66 °F-72 °F', tolerance: 'N/A' },
  { id: 157, name: 'Saison Single', mfg: 'East Coast Yeast', attenuation: '76%-78%', temp: '75 °F-82 °F', tolerance: 'N/A' },
  { id: 158, name: 'Burton Union', mfg: 'East Coast Yeast', attenuation: '73%-75%', temp: '64 °F-69 °F', tolerance: 'N/A' },
  { id: 159, name: 'British Mild', mfg: 'East Coast Yeast', attenuation: '66%-70%', temp: '60 °F-68 °F', tolerance: 'N/A' },
  { id: 160, name: 'Kolschbier', mfg: 'East Coast Yeast', attenuation: '75%-78%', temp: '58 °F-66 °F', tolerance: 'N/A' },
  { id: 161, name: 'Kellerbier', mfg: 'East Coast Yeast', attenuation: '74%-76%', temp: '46 °F-54 °F', tolerance: 'N/A' },
  { id: 162, name: 'Northeast Ale', mfg: 'East Coast Yeast', attenuation: '73%-75%', temp: '65 °F-70 °F', tolerance: 'N/A' },
  { id: 163, name: 'Blanche Yeast', mfg: 'Brewferm', attenuation: 'Any', temp: '64 °F-73 °F', tolerance: 'N/A' },
  { id: 164, name: 'Lager Yeast', mfg: 'Brewferm', attenuation: 'Any', temp: '50 °F-59 °F', tolerance: 'N/A' },
  { id: 165, name: 'Top Yeast', mfg: 'Brewferm', attenuation: 'Any', temp: '64 °F-77 °F', tolerance: 'N/A' },
  { id: 166, name: 'Cooper Ale', mfg: 'Coopers', attenuation: 'Any', temp: '62 °F-72 °F', tolerance: 'N/A' },
  { id: 167, name: 'BRY-97 American West Coast Ale', mfg: 'Danstar', attenuation: '75%-80%', temp: '59 °F-72 °F', tolerance: '12%' },
  { id: 168, name: 'Belle Saison Belgian Saison-Style', mfg: 'Danstar', attenuation: '75%-80%', temp: '59 °F-95 °F', tolerance: '14%' },
  { id: 169, name: 'CBC-1 Yeast for Cask &amp; Bottle Conditioning', mfg: 'Danstar', attenuation: '70%-75%', temp: '68 °F-77 °F', tolerance: '12%' },
  { id: 170, name: 'Diamond Lager', mfg: 'Danstar', attenuation: '75%-80%', temp: '50 °F-59 °F', tolerance: '7%' },
  { id: 171, name: 'Munich Wheat', mfg: 'Danstar', attenuation: '75%-80%', temp: '63 °F-76 °F', tolerance: '7%' },
  { id: 172, name: 'Nottingham Ale', mfg: 'Danstar', attenuation: '75%-80%', temp: '50 °F-73 °F', tolerance: '9%' },
  { id: 173, name: 'Windsor British Style', mfg: 'Danstar', attenuation: '70%-75%', temp: '59 °F-72 °F', tolerance: '7%' },
  { id: 174, name: 'Craft Series Cider Yeast', mfg: 'Mangrove Jack\'s', attenuation: '75%-80%', temp: '54 °F-82 °F', tolerance: 'N/A' },
  { id: 175, name: 'Newcastle Dark Ale Yeast', mfg: 'Mangrove Jack\'s', attenuation: '70%-75%', temp: '64 °F-72 °F', tolerance: 'N/A' },
  { id: 176, name: 'British Ale Yeast', mfg: 'Mangrove Jack\'s', attenuation: '75%-80%', temp: '57 °F-72 °F', tolerance: 'N/A' },
  { id: 177, name: 'Workhorse Yeast', mfg: 'Mangrove Jack\'s', attenuation: '75%-80%', temp: '68 °F-90 °F', tolerance: 'N/A' },
  { id: 178, name: 'Bavarian Wheat Yeast', mfg: 'Mangrove Jack\'s', attenuation: '70%-75%', temp: '59 °F-86 °F', tolerance: 'N/A' },
  { id: 179, name: 'Belgian Ale Yeast', mfg: 'Mangrove Jack\'s', attenuation: '80%-85%', temp: '79 °F-90 °F', tolerance: '14%' },
  { id: 180, name: 'US West Coast Yeast', mfg: 'Mangrove Jack\'s', attenuation: '75%-80%', temp: '59 °F-74 °F', tolerance: 'N/A' },
  { id: 181, name: 'Burton Union Yeast', mfg: 'Mangrove Jack\'s', attenuation: '75%-80%', temp: '62 °F-74 °F', tolerance: 'N/A' },
  { id: 182, name: 'Bohemian Lager Yeast', mfg: 'Mangrove Jack\'s', attenuation: '75%-80%', temp: '50 °F-59 °F', tolerance: 'N/A' },
  { id: 183, name: 'German Ale II', mfg: 'White Labs', attenuation: '73%-80%', temp: '65 °F-70 °F', tolerance: '10%' },
  { id: 184, name: 'Southwold Ale', mfg: 'White Labs', attenuation: '68%-75%', temp: '66 °F-69 °F', tolerance: '10%' },
  { id: 185, name: 'Premium Bitter Ale', mfg: 'White Labs', attenuation: '70%-75%', temp: '67 °F-70 °F', tolerance: '10%' },
  { id: 186, name: 'Klassic Ale Yeast', mfg: 'White Labs', attenuation: '66%-74%', temp: '66 °F-70 °F', tolerance: '10%' },
  { id: 187, name: 'British Cask Ale', mfg: 'Wyeast', attenuation: '74%-77%', temp: '63 °F-72 °F', tolerance: 'N/A' },
  { id: 188, name: 'Burton IPA Blend', mfg: 'Wyeast', attenuation: '71%-74%', temp: '64 °F-74 °F', tolerance: '10%' },
  { id: 189, name: 'West Coast IPA', mfg: 'Wyeast', attenuation: '73%-80%', temp: '62 °F-74 °F', tolerance: '10%' },
  { id: 190, name: 'European Ale Yeast', mfg: 'Wyeast', attenuation: '67%-71%', temp: '62 °F-72 °F', tolerance: '10%' },
  { id: 191, name: 'Belgian Stout', mfg: 'Wyeast', attenuation: '70%-85%', temp: '65 °F-75 °F', tolerance: '12%' },
  { id: 192, name: 'English Special Bitter Yeast', mfg: 'Wyeast', attenuation: '68%-72%', temp: '64 °F-72 °F', tolerance: '9%' },
  { id: 193, name: 'Thames Valley II Yeast', mfg: 'Wyeast', attenuation: '72%-78%', temp: '60 °F-70 °F', tolerance: '10%' },
  { id: 194, name: 'Cerveza Mexicana Lager', mfg: 'Wyeast', attenuation: '71%-76%', temp: '48 °F-56 °F', tolerance: '9%' },
  { id: 195, name: 'European Lager II', mfg: 'Wyeast', attenuation: '73%-77%', temp: '46 °F-56 °F', tolerance: '9%' },
  { id: 196, name: 'Rasenmäher Lager Yeast', mfg: 'Wyeast', attenuation: '73%-77%', temp: '48 °F-68 °F', tolerance: '9%' },
  { id: 197, name: 'North American Lager', mfg: 'Wyeast', attenuation: '70%-76%', temp: '48 °F-56 °F', tolerance: '9%' },
  { id: 198, name: 'Munich Lager II', mfg: 'Wyeast', attenuation: '72%-74%', temp: '52 °F-62 °F', tolerance: '10%' },
  { id: 199, name: 'Hella Bock', mfg: 'Wyeast', attenuation: '70%-74%', temp: '48 °F-56 °F', tolerance: '12%' },
  { id: 200, name: 'Kölsch II', mfg: 'Wyeast', attenuation: '73%-77%', temp: '55 °F-70 °F', tolerance: '10%' },
  { id: 201, name: 'Staro Prague Lager Yeast', mfg: 'Wyeast', attenuation: '70%-74%', temp: '50 °F-58 °F', tolerance: '11%' },
  { id: 202, name: 'Berliner-Weisse Blend', mfg: 'Wyeast', attenuation: '73%-77%', temp: '68 °F-72 °F', tolerance: '6%' },
  { id: 203, name: 'De Bom Sour Blend', mfg: 'Wyeast', attenuation: '75%-85%', temp: '80 °F-85 °F', tolerance: '10%' },
  { id: 204, name: 'Oud Bruin Blend', mfg: 'Wyeast', attenuation: '70%-80%', temp: '80 °F-85 °F', tolerance: '10%' },
  { id: 205, name: 'Belgian Lambic Blend', mfg: 'Wyeast', attenuation: '70%-80%', temp: '63 °F-75 °F', tolerance: '11%' },
  { id: 206, name: 'Leuven Pale Ale Yeast', mfg: 'Wyeast', attenuation: '75%-78%', temp: '65 °F-80 °F', tolerance: '12%' },
  { id: 207, name: 'Belgian Schelde Ale', mfg: 'Wyeast', attenuation: '73%-77%', temp: '62 °F-74 °F', tolerance: '11%' },
  { id: 208, name: 'Biere de Garde', mfg: 'Wyeast', attenuation: '74%-79%', temp: '70 °F-84 °F', tolerance: '12%' },
  { id: 209, name: 'Farmhouse Ale', mfg: 'Wyeast', attenuation: '74%-79%', temp: '70 °F-84 °F', tolerance: '12%' },
  { id: 210, name: 'Flanders Golden Ale Yeast', mfg: 'Wyeast', attenuation: '74%-78%', temp: '64 °F-80 °F', tolerance: '12%' },
  { id: 211, name: 'Roselare Belgian Blend', mfg: 'Wyeast', attenuation: '80%+', temp: '55 °F-80 °F', tolerance: '11%' },
  { id: 212, name: 'Trappist Blend', mfg: 'Wyeast', attenuation: '75%-80%', temp: '68 °F-85 °F', tolerance: '12%' },
  { id: 213, name: 'Dutch Castle', mfg: 'Wyeast', attenuation: '74%-79%', temp: '65 °F-80 °F', tolerance: '12%' },
  { id: 214, name: 'Canadian/Belgian Ale', mfg: 'Wyeast', attenuation: '75%-79%', temp: '65 °F-80 °F', tolerance: '12%' },
  { id: 215, name: 'Sweet Mead', mfg: 'Wyeast', attenuation: 'Any', temp: '65 °F-75 °F', tolerance: '11%' },
  { id: 216, name: 'Lactobacillus', mfg: 'Wyeast', attenuation: 'Any', temp: '60 °F-95 °F', tolerance: 'N/A' },
  { id: 217, name: 'Brettanomyces Bruxellensis', mfg: 'Wyeast', attenuation: '80%-85%', temp: '60 °F-75 °F', tolerance: '12%' },
  { id: 218, name: 'Lactobacillus Brevis', mfg: 'Wyeast', attenuation: 'Any', temp: '60 °F-95 °F', tolerance: '9%' },
  { id: 219, name: 'Lactobacillus', mfg: 'Wyeast', attenuation: 'Any', temp: '60 °F-95 °F', tolerance: 'N/A' },
  { id: 220, name: 'Brettanomyces Lambicus', mfg: 'Wyeast', attenuation: '80%-85%', temp: '60 °F-75 °F', tolerance: '12%' },
  { id: 221, name: 'Pediococcus', mfg: 'Wyeast', attenuation: 'Any', temp: '65 °F-95 °F', tolerance: 'N/A' },
  { id: 222, name: 'Old Ale Blend', mfg: 'Wyeast', attenuation: '75%-80%', temp: '68 °F-75 °F', tolerance: '12%' },
  { id: 223, name: 'Weiss', mfg: 'mauribrew', attenuation: 'Any', temp: '59 °F-86 °F', tolerance: 'N/A' },
  { id: 224, name: 'Lager 497', mfg: 'mauribrew', attenuation: 'Any', temp: '50 °F-59 °F', tolerance: 'N/A' },
  { id: 225, name: 'Ale 514', mfg: 'mauribrew', attenuation: 'Any', temp: '68 °F-90 °F', tolerance: '10%' },
  { id: 226, name: 'Copenhagen Lager Yeast', mfg: 'White Labs', attenuation: '72%-78%', temp: '50 °F-58 °F', tolerance: '10%' },
  { id: 227, name: 'ROGUE Pacman Yeast ', mfg: 'Wyeast', attenuation: '72%-78%', temp: '60 °F-72 °F', tolerance: '12%' },
  { id: 228, name: 'Chico Ale', mfg: 'RVA', attenuation: '70%-75%', temp: '67 °F-73 °F', tolerance: '11%' },
  { id: 229, name: 'Boston Ale', mfg: 'RVA', attenuation: '74%-80%', temp: '65 °F-73 °F', tolerance: '11%' },
  { id: 230, name: 'Pacman Ale', mfg: 'RVA', attenuation: '74%-78%', temp: '62 °F-72 °F', tolerance: '12%' },
  { id: 231, name: 'Hoptopper Ale', mfg: 'RVA', attenuation: '75%-80%', temp: '64 °F-76 °F', tolerance: '11%' },
  { id: 232, name: 'Chiswick Ale', mfg: 'RVA', attenuation: '65%-72%', temp: '65 °F-70 °F', tolerance: '8%' },
  { id: 233, name: 'Manchester Ale', mfg: 'RVA', attenuation: '70%-75%', temp: '65 °F-72 °F', tolerance: '10%' },
  { id: 234, name: 'Scotch Ale', mfg: 'RVA', attenuation: '70%-75%', temp: '65 °F-70 °F', tolerance: '11%' },
  { id: 235, name: 'Dublin Ale', mfg: 'RVA', attenuation: '70%-75%', temp: '65 °F-70 °F', tolerance: '12%' },
  { id: 236, name: 'German Ale I', mfg: 'RVA', attenuation: '70%-76%', temp: '60 °F-68 °F', tolerance: '10%' },
  { id: 237, name: 'Trappist Ale I', mfg: 'RVA', attenuation: '75%-80%', temp: '65 °F-72 °F', tolerance: '12%' },
  { id: 238, name: 'Trappist Ale II', mfg: 'RVA', attenuation: '75%-80%', temp: '65 °F-72 °F', tolerance: '12%' },
  { id: 239, name: 'Trappist Ale III', mfg: 'RVA', attenuation: '75%-80%', temp: '65 °F-72 °F', tolerance: '12%' },
  { id: 240, name: 'Trappist Ale IV', mfg: 'RVA', attenuation: '75%-80%', temp: '65 °F-72 °F', tolerance: '12%' },
  { id: 241, name: 'Belgian 1833 Ale', mfg: 'RVA', attenuation: '73%-80%', temp: '67 °F-70 °F', tolerance: '8%' },
  { id: 242, name: 'Belgian Gnome Ale', mfg: 'RVA', attenuation: '73%-80%', temp: '67 °F-75 °F', tolerance: '11%' },
  { id: 243, name: 'Verboten Ale', mfg: 'RVA', attenuation: '70%-75%', temp: '65 °F-75 °F', tolerance: '12%' },
  { id: 244, name: 'Golden Strong Ale', mfg: 'RVA', attenuation: '73%-80%', temp: '68 °F-75 °F', tolerance: '13%' },
  { id: 245, name: 'Saison I', mfg: 'RVA', attenuation: '65%-75%', temp: '75 °F-85 °F', tolerance: '10%' },
  { id: 246, name: 'Saison II', mfg: 'RVA', attenuation: '75%-82%', temp: '67 °F-77 °F', tolerance: '10%' },
  { id: 247, name: 'Ghost Ale', mfg: 'RVA', attenuation: '77%-84%', temp: '65 °F-80 °F', tolerance: '10%' },
  { id: 248, name: 'American Lager', mfg: 'RVA', attenuation: '75%-80%', temp: '50 °F-55 °F', tolerance: '8%' },
  { id: 249, name: 'München Lager', mfg: 'RVA', attenuation: '75%-80%', temp: '58 °F-65 °F', tolerance: '12%' },
  { id: 250, name: 'Oktoberfest Lager', mfg: 'RVA', attenuation: '65%-73%', temp: '52 °F-58 °F', tolerance: '12%' },
  { id: 251, name: 'Czech Lager', mfg: 'RVA', attenuation: '75%-80%', temp: '50 °F-55 °F', tolerance: '8%' },
  { id: 252, name: 'Flagship', mfg: 'Imperial Organic Yeast', attenuation: '73%-77%', temp: '60 °F-72 °F', tolerance: 'N/A' },
  { id: 253, name: 'Pub', mfg: 'Imperial Organic Yeast', attenuation: '69%-74%', temp: '64 °F-70 °F', tolerance: 'N/A' },
  { id: 254, name: 'House', mfg: 'Imperial Organic Yeast', attenuation: '73%-75%', temp: '62 °F-70 °F', tolerance: 'N/A' },
  { id: 255, name: 'Darkness', mfg: 'Imperial Organic Yeast', attenuation: '71%-75%', temp: '62 °F-72 °F', tolerance: 'N/A' },
  { id: 256, name: 'Barbarian', mfg: 'Imperial Organic Yeast', attenuation: '73%-74%', temp: '62 °F-70 °F', tolerance: 'N/A' },
  { id: 257, name: 'Independence', mfg: 'Imperial Organic Yeast', attenuation: '72%-76%', temp: '60 °F-72 °F', tolerance: 'N/A' },
  { id: 258, name: 'Four Square', mfg: 'Imperial Organic Yeast', attenuation: '68%-72%', temp: '64 °F-72 °F', tolerance: 'N/A' },
  { id: 259, name: 'Joystick', mfg: 'Imperial Organic Yeast', attenuation: '73%-77%', temp: '60 °F-70 °F', tolerance: 'N/A' },
  { id: 260, name: 'Sovereign', mfg: 'Imperial Organic Yeast', attenuation: '73%-77%', temp: '60 °F-70 °F', tolerance: 'N/A' },
  { id: 261, name: 'Citrus', mfg: 'Imperial Organic Yeast', attenuation: '74%-78%', temp: '67 °F-80 °F', tolerance: 'N/A' },
  { id: 262, name: 'Kaiser', mfg: 'Imperial Organic Yeast', attenuation: '73%-77%', temp: '56 °F-65 °F', tolerance: 'N/A' },
  { id: 263, name: 'Stefon', mfg: 'Imperial Organic Yeast', attenuation: '73%-77%', temp: '63 °F-73 °F', tolerance: 'N/A' },
  { id: 264, name: 'Deiter', mfg: 'Imperial Organic Yeast', attenuation: '73%-77%', temp: '60 °F-69 °F', tolerance: 'N/A' },
  { id: 265, name: 'Triple Double', mfg: 'Imperial Organic Yeast', attenuation: '74%-78%', temp: '65 °F-77 °F', tolerance: 'N/A' },
  { id: 266, name: 'Triple Napoleon', mfg: 'Imperial Organic Yeast', attenuation: '77%-83%', temp: '65 °F-78 °F', tolerance: 'N/A' },
  { id: 267, name: 'Gnome', mfg: 'Imperial Organic Yeast', attenuation: '72%-76%', temp: '65 °F-75 °F', tolerance: 'N/A' },
  { id: 268, name: 'Workhorse', mfg: 'Imperial Organic Yeast', attenuation: '72%-77%', temp: '65 °F-75 °F', tolerance: 'N/A' },
  { id: 269, name: 'Rustic', mfg: 'Imperial Organic Yeast', attenuation: '72%-76%', temp: '68 °F-80 °F', tolerance: 'N/A' },
  { id: 270, name: 'Monastic', mfg: 'Imperial Organic Yeast', attenuation: '74%-78%', temp: '68 °F-78 °F', tolerance: 'N/A' },
  { id: 271, name: 'Fish Finder', mfg: 'Imperial Organic Yeast', attenuation: '74%-78%', temp: '65 °F-73 °F', tolerance: 'N/A' },
  { id: 272, name: 'Whiteout', mfg: 'Imperial Organic Yeast', attenuation: '72%-76%', temp: '62 °F-72 °F', tolerance: 'N/A' },
  { id: 273, name: 'Global', mfg: 'Imperial Organic Yeast', attenuation: '73%-77%', temp: '46 °F-56 °F', tolerance: 'N/A' },
  { id: 274, name: 'Fest', mfg: 'Imperial Organic Yeast', attenuation: '71%-75%', temp: '46 °F-56 °F', tolerance: 'N/A' },
  { id: 275, name: 'Gateway', mfg: 'Imperial Organic Yeast', attenuation: '72%-76%', temp: '47 °F-55 °F', tolerance: 'N/A' },
  { id: 276, name: 'Harvest', mfg: 'Imperial Organic Yeast', attenuation: '70%-74%', temp: '50 °F-60 °F', tolerance: 'N/A' },
  { id: 277, name: 'Que Bueno', mfg: 'Imperial Organic Yeast', attenuation: '73%-77%', temp: '47 °F-55 °F', tolerance: 'N/A' },
  { id: 278, name: 'Cablecar', mfg: 'Imperial Organic Yeast', attenuation: '71%-75%', temp: '55 °F-65 °F', tolerance: 'N/A'}
].map(y => ({
  id: y.id,
  name: y.name,
  mfg: y.mfg,
  tolerance: parseInt(y.tolerance),
  tempLow: parseInt(y.temp.split('-')[0]),
  tempHigh: parseInt(y.temp.split('-')[1]),
  attenuationLow: parseInt(y.attenuation.split('-')[0]),
  attenuationHigh: parseInt(y.attenuation.split('-')[1])
}));

export default YeastLookup;